backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_SERVICE_HOST}
      port: ${POSTGRES_SERVICE_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  github:
    - host: github.com
      apps:
        - $include: credentials/backstage-app-credentials.yaml

catalog:
  locations:
    - type: url
      target: https://github.com/thefrontside/playhouse/blob/main/catalog-info.yaml
    - type: url
      target: https://github.com/thefrontside/playhouse/blob/main/templates/standard-microservice/template.yaml
      rules:
        - allow: [Template]
