backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_SERVICE_HOST}
      port: ${POSTGRES_SERVICE_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  github:
    - host: github.com
      apps:
        - $include: credentials/backstage-app-credentials.yaml

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  session:
    secret: ${AUTH_SESSION_CLIENT_SECRET}
  environment: production
  providers:
    auth0:
      production:
        domain: ${AUTH_AUTH0_DOMAIN_ID}
        clientId: ${AUTH_AUTH0_CLIENT_ID}
        clientSecret: ${AUTH_AUTH0_CLIENT_SECRET}
        audience: ${AUTH_AUTH0_AUDIENCE}
        connection: ${AUTH_AUTH0_CONNECTION}
        connectionScope: ${AUTH_AUTH0_CONNECTION_SCOPE}
