apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-annotation
  title: Add annotation to a catalog-info.yaml file
  description: Opens a PR with updates to a catalog-info.yaml file.

spec:
  owner: john@example.com
  type: service
  parameters:
    - title: catalog-info.yaml
      required: ['catalogInfoUrl', 'branch']
      properties:
        catalogInfoUrl:
          title: The catalog-info.yaml url
          type: string
          description: The catalog-info.yaml file to add the annotation to
          ui:readonly: true
        branch:
          title: Branch
          type: string
          description: the branch name for the pull request
          default: add-annotation-to-catalog-info

  steps:
    - id: fetchPlain
      name: Fetch the file
      action: fetch:plain
      input:
        url: ${{ parameters.catalogInfoUrl }}

    - id: add-annotation
      name: AddAnnotation
      action: backend:add-annotation
      input:
        # This file must exist at this path in the repo referenced above
        url: ${{ parameters.catalogInfoUrl }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=playhouse&owner=frontside
        title: Add annotation to config-info.yaml
        description: update description
        targetPath: not-sure-what-goes-here
        branchName: ${{ steps.fetchPlain.output.branch }}


