apiVersion: v1
kind: Secret
metadata:
  name: backstage-credentials
data:
  backstage-app-credentials.yaml: {{ required "You must provide credentials for the Github Frontside Backstage App" .Values.backstageGithubCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
type: Opaque
data:
  HUMANITEC_TOKEN: {{ required "You must provide a Humanitec token" .Values.humanitecToken | b64enc}}
  AUTH_SESSION_CLIENT_SECRET: {{ required "You must provide a Auth Session Client Secret" .Values.authSessionClientSecret | b64enc}}
  AUTH_AUTH0_CLIENT_SECRET: {{ required "You must provide a Auth0 Client Secret" .Values.auth0ClientSecret | b64enc}}