apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: documentation-onboarding
  title: Documentation Onboarding
  description: Workflow that adds annotation to the component and add docs code.
spec:
  owner: john@example.com
  type: service
  parameters:
    - title: Select file and ban
      required: ['catalogInfoUrl', 'branch']
      properties:
        catalogInfoUrl:
          title: The catalog-info.yaml url
          type: string
          description: The catalog-info.yaml file to add the annotation to
          ui:readonly: true
        entityRef:
          title: EntityRef
          type: string
          description: the entity ref of
          ui:widget: hidden
        branch:
          title: Branch
          type: string
          description: the branch name for the pull request
          default: add-annotation-to-catalog-info

  steps:
    - id: fetchPlain
      name: Fetch the file
      action: fetch:plain
      input:
        url: ${{ parameters.catalogInfoUrl }}
        
    - id: add-annotation
      name: AddAnnotation
      action: backend:add-annotation
      input:
        # This file must exist at this path in the repo referenced above
        url: ${{ parameters.catalogInfoUrl }}
        entityRef: ${{ parameters.entityRef }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=playhouse&owner=thefrontside
        title: Add annotation to config-info.yaml
        description: update description
        targetPath: "."
        sourcePath: ${{ steps['add-annotation'].output.path }}
        branchName: ${{ parameters.branch }}