name: Create Deploy Preview Environment

on:
  pull_request:
    types:
      - labeled

env:
  ARTEFACTS_FILTER: us-central1-docker.pkg.dev/frontside-humanitec/frontside-artifacts/backstage

jobs:
  create-environment:
    name: Create And Setup Automation
    if: github.event.label.name == 'deploy-preview'
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Number
        run: echo "PR_NUMBER=`echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'`" >> $GITHUB_ENV

      - name: Create Environment
        run: |-
          curl \
            --request POST 'https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG_ID }}/apps/backstage/envs' \
            --header 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "from_deploy_id": "'development'",
                "id": "'pr$PR_NUMBER'",
                "name": "'pr$PR_NUMBER'",
                "type": "'preview'",
            }'
      - name: Add Automation Rule
        run: |-
          curl \
            --request POST 'https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG_ID }}/apps/backstage/envs/pr${{ env.PR_NUMBER }}/rules' \
            --header 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "active": "'true'",
                "artefacts_filter": "'$ARTEFACTS_FILTER'",
                "match_ref": "'refs/heads/$PR_NUMBER/merge'",
                "type": "'update'",
            }'
