name: Backstage Deploy

on:
  push:
    branches: main

concurrency: ${{ github.ref }}

env:
  IMAGE: 'northamerica-northeast1-docker.pkg.dev/frontside-humanitec/frontside-artifacts/backstage'
  USE_GKE_GCLOUD_AUTH_PLUGIN: true

jobs:
  deploy:
    name: Cloud Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v3

      - name: Google Cloud Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.CLOUD_WORKLOAD_PROVIDER}}
          service_account: ${{ secrets.CLOUD_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin

      - name: Install/Build Backstage
        run: yarn && yarn tsc && yarn build

      - name: Set Tag with SHA
        run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-6`" >> $GITHUB_ENV

      - name: Cloud Build & Push to Artifacts Registry
        run: gcloud builds submit . --config=cloudbuild.yaml --substitutions=_IMAGE="$IMAGE:$TAG"

      - name: Inform Humanitec
        run: |-
          curl \
            --request POST 'https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG_ID }}/images/backstage/builds' \
            --header 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "branch": "'$GITHUB_REF_NAME'",
                "commit": "'$GITHUB_SHA'",
                "image": "'$IMAGE:$TAG'",
                "tags": ["'$TAG'"]
            }'
