name: Publish Releases

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish Releases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org
    - uses: volta-cli/action@v3
    - uses: thefrontside/actions/synchronize-with-npm@v2
      with:
        INSTALL_SCRIPT: yarn install --frozen-lockfile && yarn tsc && yarn build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
